### ISSUE TITLE
Build User/Password Challenge before entering store.

### ISSUE THREAD

**Issue by ridingwithrails** [ridingwithrails/digi-ticks#4]
Use Store.py as a reference.

When a user starts store
They should be asked for a username and then a password.

Password should not be visible.

**Comment by OwaTay** [comment]
I'm pretty sure @DoniTay fixed it. Hopefully he did but anyways Good Luck!

**Comment by DoniTay** [comment]
@OwaTay I'm working on it right now with @ridingwithrails.

**Comment by OwaTay** [comment]
Oh, then Good Luck!

**Comment by DoniTay** [comment]
@OwaTay It might take longer to get the Passwords and Username part built, @ridingwithrails  is having problem with his computer.

**Comment by OwaTay** [comment]
@DoniTay Hopefully he can fix it!

**Comment by DoniTay** [comment]
Yes.

**Comment by OwaTay** [comment]
@DoniTay it seems @ridingwithrails is trying to make Dockerfile python.

**Comment by DoniTay** [comment]
@OwaTay  @ridingwithrails  fixed it!

**Comment by OwaTay** [comment]
Nice!

**Comment by OwaTay** [comment]
@DoniTay Currently @ridingwithrails is setting our code up.
